# Generated by Django 5.1.5 on 2025-02-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capital', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
                ('currency', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('flag', models.ImageField(upload_to='flags/')),
            ],
        ),
    ]
