# Generated by Django 5.1.4 on 2025-02-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_capital_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='flag',
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='language',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.IntegerField(max_length=100),
        ),
    ]
