# Generated by Django 5.1.4 on 2025-02-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_capital_app', '0002_remove_country_flag_alter_country_capital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.CharField(max_length=100),
        ),
    ]
